### ISSUE TITLE
Async await support

### ISSUE THREAD

**Issue by ullstrm** [danielsaidi/Mockery#14]
When creating a `MockReference` to an async function, one gets this error:

`Cannot pass function of type '() async throws -> ()' to parameter expecting synchronous function`

<img width="979" alt="Screenshot 2022-05-02 at 17 06 31" src="https://user-images.githubusercontent.com/6592776/166257783-aec8f7cd-a9a4-44ed-9f05-f3b5dbf64981.png">

**Comment by danielsaidi** [comment]
Great find! I really hope there's a clean way to get this working.

**Comment by danielsaidi** [comment]
I have merged the PR by @tboogh that adds this 🎉 

I will adjust the docs, then release a 1.1 wit these new capabilities.
